version: '3'
services:
  vault:
    build: ./docker/vault
    image: vaulthome
    ports:
      - 8200:8200
    volumes:
      - vaultfile:/vault/file
      - vaultlogs:/vault/logs
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

volumes:
  vaultfile:
  vaultlogs:
